# Generated by Django 2.2.4 on 2019-08-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('Fixture_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Fixture_Home_Team', models.IntegerField()),
                ('Fixture_Away_Team', models.IntegerField()),
                ('Fixture_Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('Team_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Team_Name', models.CharField(max_length=200)),
                ('Team_Stadium', models.CharField(max_length=500)),
                ('Team_Location', models.CharField(max_length=500)),
            ],
        ),
    ]
